name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: >
            [
              {
                  "id": "github",
                  "url": "https://maven.pkg.github.com/mahabaleshwars/TestA"
              }
            ]
          servers: >
            [
              {
                "id":"github",
                "username":"${{ github.actor }}",
                "password":"${{ secrets.REPO_TOKEN }}"
              }
            ]
      - name: Print settings.xml
        run: cat /home/runner/.m2/settings.xml
      - name: Build with Maven and Run unit Test
        run: mvn --batch-mode --update-snapshots verify

  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: >
            [
              {
                  "id": "github",
                  "url": "https://maven.pkg.github.com/mahabaleshwars/TestA"
              }
            ]
          servers: >
            [
              {
                "id":"github",
                "username":"${{ github.actor }}",
                "password":"${{ secrets.REPO_TOKEN }}"
              }
            ]
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
